# Copyright (c) 2025 Darren Soothill
# Licensed under the MIT License

version: 2

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocyclo
    - misspell
    - revive
    - unconvert
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    enable:
      - shadow
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - unused
    - path: monitoring/power\.go
      linters:
        - unparam
    - path: pkg/logger/logger\.go
      linters:
        - unparam
